### ISSUE TITLE
Error on executing actions through CLI or webinterface

### ISSUE THREAD

**Issue by lampi87** [guh/guh#265]
Hello,

on executing any actions (tested with tutorial buttons) an error occurs and guhd is stopped.
Steps to reproduce:
start guhd like `sudo guhd -n -d Buttons` in terminal 2
start `guh-cli` in terminal 1
Create new device for simple button or power button
Execute action

Actual result:
guhd is stopped in terminal 2 with no additional output
Output in terminal 1:
```
========================================================

The ParamType looks like this:
{
    "defaultValue": false,
    "name": "power",
    "type": "Bool"
}
None

Bye, have a nice day! :)
Traceback (most recent call last):
  File "/usr/bin/guh-cli", line 56, in <module>
    mainmenu.start(args.host, args.port)
  File "/usr/lib/python2.7/dist-packages/guh/mainmenu.py", line 589, in start
    processmenu(menu_data)
  File "/usr/lib/python2.7/dist-packages/guh/mainmenu.py", line 675, in processmenu
    processmenu(menu['options'][getin], menu)
  File "/usr/lib/python2.7/dist-packages/guh/mainmenu.py", line 664, in processmenu
    methodCall()
  File "/usr/lib/python2.7/dist-packages/guh/mainmenu.py", line 341, in method_execute_action
    actions.execute_action()
  File "/usr/lib/python2.7/dist-packages/guh/actions.py", line 85, in execute_action
    response = guh.send_command("Actions.ExecuteAction", params)
  File "/usr/lib/python2.7/dist-packages/guh/guh.py", line 64, in send_command
    data = tn.read_until("\n}\n")
  File "/usr/lib/python2.7/telnetlib.py", line 294, in read_until
    return self._read_until_with_poll(match, timeout)
  File "/usr/lib/python2.7/telnetlib.py", line 343, in _read_until_with_poll
    return self.read_very_lazy()
  File "/usr/lib/python2.7/telnetlib.py", line 455, in read_very_lazy
    raise EOFError, 'telnet connection closed'
EOFError: telnet connection closed
```
Used version from Ubuntu repositories, `Application: guhd 0.7.0+201601040048~098c15f~wily started as root.`

Best regards,
Alex

**Comment by t-mon** [comment]
Hello Alex! Thanks for the bug report. Since the last two versions of the `libguh1-dev` there seems to be a linker error in the lib. This issue is known and I am working on it. I guess there is missing the `-rpath` parameter for the linker.

When you try to execute an action with a plugin built with the `libguh1-dev`, the execute action function will not be executed correctly (lib link error). I'll let you know when I found the issue in the build environment. Sorry for the inconvenience.

**Comment by lampi87** [comment]
Thank you very much for your quick response!

**Comment by t-mon** [comment]
The lib should be fixed now, and the examples are updated. This was a very strange linker error! Thanks for reporting it!

Please make an update before trying again:
* update guh: `sudo apt-get update && sudo apt-get upgrade`
* update plugin source code `git pull origin master`

If it works for you now, please close this issue! good luck! :)

**Comment by lampi87** [comment]
Thank you very much, it works now!
